project_id = "dxdknkeexankgtkpeuvt"

[functions.power-dialer-log]
verify_jwt = true

[functions.power-dialer-next]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.import-leads]
verify_jwt = true

[functions.realtime-objection-handler]
verify_jwt = false

[functions.api-leads]
verify_jwt = false
